// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XcaNet.Storage.Persistence;

#nullable disable

namespace XcaNet.Storage.Persistence.Migrations
{
    [DbContext(typeof(XcaNetDbContext))]
    partial class XcaNetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("XcaNet.Storage.Persistence.Entities.AppSettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("XcaNet.Storage.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("OccurredUtc");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("XcaNet.Storage.Persistence.Entities.AuthorityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentAuthorityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PrivateKeyId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authorities");
                });

            modelBuilder.Entity("XcaNet.Storage.Persistence.Entities.CertificateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataFormat")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("DerData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCertificateAuthority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IssuerCertificateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyAlgorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NotAfterUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NotBeforeUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PrivateKeyId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RevocationReason")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RevocationState")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha1Thumbprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256Thumbprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Issuer");

                    b.HasIndex("IssuerCertificateId");

                    b.HasIndex("NotAfterUtc");

                    b.HasIndex("NotBeforeUtc");

                    b.HasIndex("RevocationState");

                    b.HasIndex("RevokedAtUtc");

                    b.HasIndex("SerialNumber");

                    b.HasIndex("Sha1Thumbprint");

                    b.HasIndex("Sha256Thumbprint");

                    b.HasIndex("Subject");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("XcaNet.Storage.Persistence.Entities.CertificateRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataFormat")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("DerData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyAlgorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrivateKeyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectAlternativeNames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CertificateRequests");
                });

            modelBuilder.Entity("XcaNet.Storage.Persistence.Entities.CertificateRevocationListEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CrlNumber")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("DerData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IssuerCertificateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuerDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextUpdateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PemData")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ThisUpdateUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CertificateRevocationLists");
                });

            modelBuilder.Entity("XcaNet.Storage.Persistence.Entities.CertificateTagEntity", b =>
                {
                    b.Property<Guid>("CertificateId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("CertificateId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("CertificateTags");
                });

            modelBuilder.Entity("XcaNet.Storage.Persistence.Entities.DatabaseProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptionAlgorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("KdfAlgorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("KdfIterations")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("KdfSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastOpenedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("VerifierCiphertext")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("VerifierNonce")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("VerifierTag")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("DatabaseProfiles");
                });

            modelBuilder.Entity("XcaNet.Storage.Persistence.Entities.PrivateKeyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptedPkcs8Ciphertext")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("EncryptionAlgorithm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptionNonce")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("EncryptionTag")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicKeyFingerprint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PublicKeyFingerprint");

                    b.ToTable("PrivateKeys");
                });

            modelBuilder.Entity("XcaNet.Storage.Persistence.Entities.TagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("XcaNet.Storage.Persistence.Entities.TemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Curve")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnhancedKeyUsages")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("IntendedUsage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCertificateAuthority")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyAlgorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyUsages")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PathLengthConstraint")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RsaKeySize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SignatureAlgorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectAlternativeNames")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectDefault")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<int>("ValidityDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IntendedUsage");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("IsFavorite");

                    b.HasIndex("Name");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("XcaNet.Storage.Persistence.Entities.CertificateRevocationListEntity", b =>
                {
                    b.OwnsMany("XcaNet.Storage.Persistence.Entities.CertificateRevocationListEntryEntity", "RevokedEntries", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("CertificateRevocationListId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<int>("Reason")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("RevokedAtUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SerialNumber")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Subject")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("CertificateRevocationListId");

                            b1.ToTable("CertificateRevocationListEntries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CertificateRevocationListId");
                        });

                    b.Navigation("RevokedEntries");
                });

            modelBuilder.Entity("XcaNet.Storage.Persistence.Entities.CertificateTagEntity", b =>
                {
                    b.HasOne("XcaNet.Storage.Persistence.Entities.CertificateEntity", "Certificate")
                        .WithMany("CertificateTags")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XcaNet.Storage.Persistence.Entities.TagEntity", "Tag")
                        .WithMany("CertificateTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificate");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("XcaNet.Storage.Persistence.Entities.CertificateEntity", b =>
                {
                    b.Navigation("CertificateTags");
                });

            modelBuilder.Entity("XcaNet.Storage.Persistence.Entities.TagEntity", b =>
                {
                    b.Navigation("CertificateTags");
                });
#pragma warning restore 612, 618
        }
    }
}
